# Generated by Django 4.2.13 on 2024-06-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishcollection',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
